sonar.organization=pipe-c
sonar.projectKey=Pipe-C_THOTH

# Rutas del código fuente que se analizará (normalmente la raíz '.')
sonar.sources=.

# Opcional: Exclusiones de archivos o librerías
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

# Excluir cálculo de cobertura hasta implementar suite de tests
sonar.coverage.exclusions=**
