name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Se requiere profundizar en el historial (fetch-depth: 0) para un análisis de código preciso
          fetch-depth: 0

      - name: Configurar Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas y generar cobertura
        run: npm --prefix apps/backend run test:coverage

      - name: Ejecutar SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@2f77a1ec69fb1d595b06f35ab27e97605bdef703 # v5.3.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}